### ISSUE TITLE
Unable to run container, find.exe is missing

### ISSUE THREAD

**Issue by MacDennis76** [pbering/solrwin#1]
Hi,

First of all, many thanks for all the effort you have put into the creation of all these Docker images. It is very much appreciated, keep up the good work!

I was toying with the solrwin Dockerfile and have been unsuccessful in getting it to run. If I either use docker-compose up or docker run then I am greeted with the following error message:
solrwin_1  | 'find' is not recognized as an internal or external command,
solrwin_1  | operable program or batch file.

On a normal Windows OS the find.exe program is present in C:\Windows\System32. 

I looked in the nanoserver:sac2016 and nanoserver:1709 images but the find.exe program seems to be missing.

The thing is, solr.cmd has a dependency on find.exe so it will not start. Any ideas?

Quick fix for in the Dockerfile which seems to be working:
COPY --from=builder /windows/system32/find.exe /windows/system32/

With kind regards,
Dennis Velthuis

**Comment by pbering** [comment]
Thank you for your feedback, much appreciated! I've been seeing the same error but just ignored it, since it looks like it's only being used to find out if any existing solr instances is running on the same port, see [https://github.com/apache/lucene-solr/blob/master/solr/bin/solr.cmd](https://github.com/apache/lucene-solr/blob/master/solr/bin/solr.cmd). 

My compose output looks like this:
````
Creating solrwin_solrwin_1 ... done
Attaching to solrwin_solrwin_1
solrwin_1  | 'find' is not recognized as an internal or external command,
solrwin_1  | operable program or batch file.
solrwin_1  | 2018-02-25 10:30:16.419 INFO  (main) [   ] o.e.j.s.Server jetty-9.3.14.v20161028
solrwin_1  | 2018-02-25 10:30:17.755 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter  ___      _       Welcome to Apache Solr´┐¢ version 6.6.2
solrwin_1  | 2018-02-25 10:30:17.771 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter / __| ___| |_ _   Starting in standalone mode on port 8983
solrwin_1  | 2018-02-25 10:30:17.771 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter \__ \/ _ \ | '_|  Install dir: c:\solr
solrwin_1  | 2018-02-25 10:30:17.834 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter |___/\___/_|_|    Start time: 2018-02-25T10:30:17.771Z
solrwin_1  | 2018-02-25 10:30:17.896 INFO  (main) [   ] o.a.s.c.SolrResourceLoader Using system property solr.solr.home: g:/
solrwin_1  | 2018-02-25 10:30:17.912 INFO  (main) [   ] o.a.s.c.SolrXmlConfig Loading container configuration from g:\solr.xml
solrwin_1  | 2018-02-25 10:30:18.932 INFO  (main) [   ] o.a.s.u.UpdateShardHandler Creating UpdateShardHandler HTTP client with params: socketTimeout=600000&connTimeout=60000&retry=true
solrwin_1  | 2018-02-25 10:30:20.582 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Found 0 core definitions underneath g:\
solrwin_1  | 2018-02-25 10:30:21.300 INFO  (main) [   ] o.e.j.s.Server Started @6433ms
````

And solr works fine. Do you not see something similar?

**Comment by pbering** [comment]
... and I also added your fix to get rid of the error in the output, thank you!
